import { Header } from '../../components/Header';
import { SectionLabel } from '../../components/SectionLabel';
import { RequestStaffForm } from '../../components/RequestStaffForm';

export default function RequestStaffPage(){
  return <main className="requestStaffPage">
    <section className="requestStaffHero"><Header theme="light"/><div className="pageShell requestStaffHeroGrid"><div><div className="candidateEyebrow">FOR EMPLOYERS <span>/ REQUEST STAFF</span></div><h1>Tell us what your<br/><em>operation needs<span className="accentPeriod">.</span></em></h1></div><div><p>A short, structured brief gives the Complex team the information needed to respond quickly. No account. No long onboarding process.</p><div className="requestHeroProof"><strong>03</strong><span>simple steps</span></div></div></div></section>
    <section className="requestStaffMain"><div className="pageShell requestStaffLayout"><aside><SectionLabel>BEFORE YOU START</SectionLabel><h2>Keep it simple.<br/><em>We’ll handle the detail.</em></h2><p>You don’t need to know every specification before getting in touch. Start with the basics and the team can clarify the rest with you.</p><div className="requestAsidePoints"><span><b>01</b> Sector & requirement type</span><span><b>02</b> Role, numbers, location & timing</span><span><b>03</b> Your contact details</span></div><a href="tel:02039237888" className="requestCall"><span>URGENT REQUIREMENT?</span><strong>Call 0203 923 7888</strong></a></aside><RequestStaffForm/></div></section>
    <section className="requestWhatNext"><div className="pageShell"><SectionLabel>WHAT HAPPENS NEXT</SectionLabel><div className="requestWhatGrid">{[['01','We review the brief','The team checks the sector, role, timing and operational detail.'],['02','We make contact','A specialist can clarify anything needed and discuss the requirement.'],['03','Recruitment begins','Complex moves into sourcing, matching and relevant compliance checks.']].map(([n,t,c])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{c}</p></article>)}</div></div></section>
    <footer className="siteFooter"><img className="footerMark" src="/complex-mark.png" alt=""/><div className="pageShell footerLead"><div className="footerBrand"><img className="footerLogo" src="/complex-logo-white.png" alt="Complex Recruitment"/><p>Specialist workforce solutions across Driving, Industrial and Construction.</p></div><a className="footerCall" href="tel:02039237888"><span>CALL COMPLEX</span><strong>0203 923 7888</strong><i>↗</i></a></div><div className="pageShell footerBottom"><span>© 2026 COMPLEX RECRUITMENT</span><nav><a href="/privacy">Privacy</a><a href="/cookies">Cookies</a><a href="/terms">Terms</a><a href="/modern-slavery">Modern Slavery</a></nav></div></footer>
  </main>
}
