import { Footer } from '../../../components/layout/Footer';
import { Container } from '../../../components/layout/Container';
import { SectionLabel } from '../../../components/SectionLabel';
import { ServiceHero } from '../../../components/training/ServiceHero';
import { ButtonLink } from '../../../components/ui/ButtonLink';
import { TextLink } from '../../../components/ui/TextLink';

const topics = ['Customer Service', 'Reducing Infringements', 'Vehicle Security', 'Fuel Consumption', 'Dealing With Incidents', 'Daily Driving Challenges', 'Health & Safety', 'Drivers’ Hours', 'Manual Handling', 'Road Freight Compliance'];

export default function CpcPage() {
  return <main>
    <ServiceHero kind="cpc" eyebrow={<>CPC TRAINING <span className="ml-[10px] text-[#b5b8ba] max-[640px]:hidden">/ PROFESSIONAL DEVELOPMENT</span></>} title={<>Keep knowledge current.<br /><em>Keep drivers moving.</em></>} intro="Driver CPC training designed around the practical realities of professional transport, available as full-course or split-session delivery." actionHref="#cpc-enquiry" actionLabel="Enquire About CPC" badgeLabel="PERIODIC TRAINING" badgeValue="35h" badgeCopy="Within a five-year period for HGV drivers" railItems={['35-hour Full Course', '7-hour Split Sessions', 'Professional Instructors', 'Employer Enquiries']} />
    <section className="bg-white py-[126px] max-[640px]:py-[88px]"><Container className="grid grid-cols-[1fr_.7fr] items-end gap-[100px] max-[1000px]:grid-cols-1 max-[1000px]:gap-[46px]"><div><SectionLabel>CPC AT COMPLEX</SectionLabel><h2 className="m-0 mt-[34px] text-[clamp(50px,5vw,82px)] leading-[.95] tracking-[-.055em] max-[640px]:text-5xl">Training that stays<br /><em className="not-italic text-brand-red">grounded in the job.</em></h2></div><div><p className="mb-7 max-w-[590px] text-[15px] leading-[1.72] text-[#626e74]">Complex currently delivers CPC training in partnership with AVTAV Ltd, a member of the RTITB consortium, with courses described as approved by JAUPT and DVSA. Before launch, partnership and approval wording should be reconfirmed with the client.</p><TextLink href="#cpc-enquiry">Discuss Training</TextLink></div></Container></section>
    <section className="bg-ink py-[126px] text-white max-[640px]:py-[88px]"><Container className="grid grid-cols-[.7fr_1.3fr] gap-[90px] max-[1000px]:grid-cols-1 max-[1000px]:gap-[46px]"><div className="[&_.sectionLabel]:text-white"><SectionLabel>TRAINING FORMAT</SectionLabel><h2 className="m-0 mt-[34px] text-[clamp(50px,5vw,82px)] leading-[.95] tracking-[-.055em] max-[640px]:text-5xl">One requirement.<br /><em className="not-italic text-brand-red">Two ways to complete it.</em></h2><p className="mt-7 max-w-[490px] text-sm leading-[1.7] text-[#aeb5b8]">The current Complex offering describes both a complete 35-hour course and individual 7-hour training sessions.</p></div><div className="grid grid-cols-2 gap-3 max-[640px]:grid-cols-1">{[['FULL COURSE', '35', 'hours / five days', 'A concentrated route for completing the full periodic training requirement.'], ['SPLIT COURSE', '07', 'hours / one-day sessions', 'A more flexible route for completing training across separate sessions.']].map(([label, value, unit, copy]) => <article key={label} className="group min-h-[430px] border border-white/10 bg-[#1b1d20] p-7 transition-[background-color,transform] duration-300 hover:-translate-y-[5px] hover:bg-brand-red focus-within:-translate-y-[5px] focus-within:bg-brand-red"><span className="text-[8px] font-extrabold tracking-[.17em] text-[#9da5a9] group-hover:text-white/80">{label}</span><strong className="mb-[10px] mt-[110px] block text-[100px] leading-[.8] tracking-[-.08em]">{value}</strong><small className="text-[10px] uppercase tracking-[.1em]">{unit}</small><p className="mt-6 max-w-[300px] text-xs leading-[1.6] text-[#aeb5b8] group-hover:text-white/80">{copy}</p></article>)}</div></Container></section>
    <section className="bg-surface py-[126px] max-[640px]:py-[88px]"><Container><div className="grid grid-cols-[.4fr_1fr] gap-[70px] max-[640px]:block"><SectionLabel>TRAINING TOPICS</SectionLabel><h2 className="m-0 max-[640px]:mt-7 text-[clamp(50px,5vw,82px)] leading-[.95] tracking-[-.055em] max-[640px]:text-5xl">Practical subjects for<br /><em className="not-italic text-brand-red">professional drivers.</em></h2></div><div className="mt-[70px] grid grid-cols-2 border-l border-t border-line max-[640px]:grid-cols-1">{topics.map((topic, index) => <article key={topic} className="group grid min-h-[120px] grid-cols-[40px_1fr_24px] items-center border-b border-r border-line px-[25px] py-[22px] transition-colors hover:bg-white"><span className="text-[8px] font-extrabold text-brand-red">{String(index + 1).padStart(2, '0')}</span><h3 className="m-0 text-xl tracking-[-.02em] transition-transform duration-300 group-hover:translate-x-[7px]">{topic}</h3><i className="not-italic transition-transform duration-300 group-hover:translate-x-1.5 group-hover:-translate-y-1.5">↗</i></article>)}</div></Container></section>
    <section className="bg-white py-[126px] max-[640px]:py-[88px]"><Container className="grid grid-cols-[1fr_.9fr] items-center gap-[90px] max-[1000px]:grid-cols-1 max-[1000px]:gap-[46px]"><div className="h-[570px] bg-[linear-gradient(rgba(17,18,20,.02),rgba(17,18,20,.14)),url('https://images.pexels.com/photos/13861/IMG_3496bfree.jpg?auto=compress&cs=tinysrgb&w=1800')] bg-cover bg-center grayscale-[.18] max-[640px]:h-[340px]" /><div><SectionLabel>INSTRUCTOR-LED</SectionLabel><h2 className="m-0 mt-[34px] text-[clamp(50px,5vw,82px)] leading-[.95] tracking-[-.055em] max-[640px]:text-5xl">Knowledge that<br /><em className="not-italic text-brand-red">connects to practice.</em></h2><p className="my-7 max-w-[570px] text-[15px] leading-[1.7] text-[#626e74]">The current site states that NRI-registered LGV instructors with transport-logistics training experience support delivery. The new page keeps that credibility, but presents it in a clearer and less text-heavy way.</p><div className="mb-[30px] flex flex-wrap gap-2">{['Professional driving', 'Transport logistics', 'Compliance awareness'].map(item => <span className="border border-line px-[13px] py-[11px] text-[9px] text-[#5f696e]" key={item}>{item}</span>)}</div><ButtonLink href="#cpc-enquiry" variant="dark">Plan Your Training</ButtonLink></div></Container></section>
    <section className="bg-brand-red py-[126px] text-white max-[640px]:py-[88px]" id="cpc-enquiry"><Container className="grid grid-cols-[1fr_.78fr] items-center gap-[100px] max-[1000px]:grid-cols-1 max-[1000px]:gap-[46px]"><div className="[&_.sectionLabel]:text-white"><SectionLabel>PLAN YOUR CPC</SectionLabel><h2 className="m-0 mt-[34px] text-[clamp(50px,5vw,82px)] leading-[.95] tracking-[-.055em] max-[640px]:text-5xl">Training for one driver<br /><em className="not-italic">or a wider team.</em></h2></div><div className="min-h-[330px] bg-white px-[46px] py-[42px] text-ink shadow-[0_30px_70px_rgba(17,18,20,.12)] max-[640px]:px-6"><span className="text-[8px] font-extrabold tracking-[.17em] text-[#7b858b]">CPC TRAINING ENQUIRY</span><h3 className="mb-4 mt-[45px] text-[34px] leading-[1.05] tracking-[-.04em]">Tell us what you need.</h3><p className="mb-7 text-[13px] leading-[1.65] text-[#667278]">Share whether you are enquiring as a driver or employer, approximate numbers and preferred timing. Complex can confirm available delivery options.</p><ButtonLink href="/contact" variant="dark">Make an Enquiry</ButtonLink></div></Container></section>
    <Footer variant="training" />
  </main>;
}
