import { ArrowIcon } from '../ui/ArrowIcon';
import { Container } from './Container';

type FooterProps = { variant?: 'full' | 'simple' | 'compact' | 'home' | 'training' };

const groups = {
  employers: { title: 'EMPLOYERS', links: [['Employer Solutions', '/employers'], ['Permanent Recruitment', '/employers/permanent-recruitment'], ['Request Staff', '/request-staff']] },
  candidates: { title: 'CANDIDATES', links: [['Find Jobs', '/jobs'], ['Why Complex', '/candidates'], ['Compliance & Vetting', '/compliance'], ['Driver Assessments', '/training/driver-assessments']] },
  company: { title: 'COMPANY', links: [['About', '/about'], ['Contact', '/contact']] },
  sectors: { title: 'SECTORS', links: [['Driving & Transport', '/sectors/driving'], ['Industrial & Warehouse', '/sectors/industrial'], ['Construction & Engineering', '/sectors/construction'], ['Business & Operational Support', '/sectors/business-operational-support']] },
  training: { title: 'COMPLIANCE & STANDARDS', links: [['Compliance & Vetting', '/compliance'], ['Driver Assessments', '/training/driver-assessments'], ['CPC Training', '/training/cpc']] },
} as const;

const legalLinks = [['Privacy', '/privacy'], ['Cookies', '/cookies'], ['Terms', '/terms'], ['Modern Slavery', '/modern-slavery']] as const;

export function Footer({ variant = 'full' }: FooterProps) {
  if (variant === 'compact') return <CompactFooter />;
  if (variant === 'home') return <HomeFooter />;
  const navGroups = variant === 'training' ? [groups.employers, groups.candidates, groups.training, groups.company] : [groups.employers, groups.candidates, groups.company, groups.sectors];

  return <footer id="contact" className="relative isolate overflow-hidden bg-[#0b0c0e] pb-7 text-white">
    <img className="absolute bottom-[-120px] right-[-70px] -z-[1] w-[min(430px,34vw)] opacity-[.035] grayscale brightness-[5] max-[760px]:bottom-[-80px] max-[760px]:right-[-80px] max-[760px]:w-[280px]" src="/complex-mark.png" alt="" aria-hidden="true" />
    <Container className="flex min-h-[215px] items-center justify-between gap-[60px] border-b border-white/15 max-[1100px]:min-h-[190px] max-[760px]:block max-[760px]:min-h-0 max-[760px]:pb-11 max-[760px]:pt-[72px]">
      <Brand />
      <CallComplex />
    </Container>
    {variant !== 'simple' && <Container className="grid grid-cols-4 gap-[60px] py-[62px] pb-14 max-[1100px]:gap-[35px] max-[760px]:grid-cols-2 max-[760px]:gap-x-[30px] max-[760px]:gap-y-11 max-[760px]:py-12">{navGroups.map((group) => <FooterGroup key={group.title} group={group} />)}</Container>}
    <FooterBottom />
  </footer>;
}

function Brand() { return <div className="max-w-[410px]"><img className="mb-[26px] w-[190px]" src="/complex-logo-white.png" alt="Complex Recruitment" /><p className="m-0 max-w-[340px] text-[13px] leading-[1.65] text-[#8f9aa1]">Specialist workforce solutions across four operational sectors.</p></div>; }
function CallComplex() { return <a href="tel:02039237888" aria-label="Call Complex Recruitment on 0203 923 7888" className="group grid min-w-[330px] grid-cols-[1fr_auto] items-end gap-x-[30px] gap-y-[7px] border-t border-white/25 pb-[23px] pt-[27px] outline-none transition-colors hover:border-brand-red focus-visible:border-brand-red focus-visible:ring-2 focus-visible:ring-brand-red max-[760px]:mt-12 max-[760px]:w-full max-[760px]:min-w-0"><span className="col-start-1 text-[9px] tracking-[.17em] text-[#7f898f]">CALL COMPLEX</span><strong className="col-start-1 text-[28px] tracking-[-.025em] max-[390px]:text-2xl">0203 923 7888</strong><ArrowIcon className="col-start-2 row-span-2 row-start-1 self-center text-2xl text-brand-red transition-transform duration-300 ease-complex group-hover:translate-x-[7px] group-hover:-translate-y-[7px] group-focus-visible:translate-x-[7px] group-focus-visible:-translate-y-[7px]" /></a>; }
function FooterGroup({ group }: { group: { readonly title: string; readonly links: readonly (readonly [string, string])[] } }) { return <div><h4 className="mb-6 mt-0 text-[9px] tracking-[.16em] text-[#6f797f]">{group.title}</h4>{group.links.map(([label, href]) => <a key={href} className="group mb-[13px] table text-xs text-[#c4c8ca] outline-none transition-[color,transform] hover:translate-x-1 hover:text-white focus-visible:translate-x-1 focus-visible:text-white focus-visible:ring-2 focus-visible:ring-brand-red" href={href}>{label}<i className="mt-[3px] block h-0.5 w-[14px] origin-left scale-x-0 bg-brand-red transition-transform group-hover:scale-x-100 group-focus-visible:scale-x-100" /></a>)}</div>; }
function FooterBottom({ className = '' }: { className?: string }) { return <Container className={`flex items-center justify-between border-t border-white/15 pt-6 text-[9px] tracking-[.1em] text-[#687278] max-[760px]:block max-[760px]:leading-[1.8] ${className}`}><span>© 2026 COMPLEX RECRUITMENT</span><nav aria-label="Legal" className="flex gap-[22px] max-[760px]:mt-[10px] max-[760px]:flex-wrap max-[760px]:gap-x-[18px] max-[760px]:gap-y-2">{legalLinks.map(([label, href]) => <a className="outline-none transition-colors hover:text-white focus-visible:text-white focus-visible:ring-2 focus-visible:ring-brand-red" key={href} href={href}>{label}</a>)}</nav></Container>; }
function CompactFooter() { return <footer className="bg-ink py-[34px] text-white"><Container className="grid grid-cols-[220px_1fr_auto] items-center gap-10 max-[760px]:grid-cols-1 max-[760px]:gap-[22px] max-[760px]:text-center"><img className="w-[150px] max-[760px]:mx-auto" src="/complex-logo-white.png" alt="Complex Recruitment" /><nav aria-label="Legal" className="flex justify-center gap-[26px] max-[760px]:flex-wrap">{legalLinks.map(([label, href]) => <a className="text-[10px] text-[#c6c9ca] outline-none hover:text-white focus-visible:ring-2 focus-visible:ring-brand-red" key={href} href={href}>{label}</a>)}</nav><a className="text-[13px] font-extrabold outline-none focus-visible:ring-2 focus-visible:ring-brand-red" href="tel:02039237888">0203 923 7888</a></Container></footer>; }
function HomeFooter() { return <footer id="contact" className="bg-[#0d0e10] py-20 pb-[30px] text-white"><Container className="grid grid-cols-[1.5fr_repeat(3,1fr)] gap-[60px] max-[1100px]:grid-cols-[1.4fr_repeat(3,1fr)] max-[760px]:grid-cols-2 max-[760px]:gap-x-[30px] max-[760px]:gap-y-[46px] max-[430px]:grid-cols-1"><Brand /><HomeGroup title="Employers" links={[["Employer Solutions", "/employers"], ["Permanent Recruitment", "/employers/permanent-recruitment"], ["Request Staff", "#request-staff"]]} /><HomeGroup title="Candidates" links={[["Find Jobs", "#jobs"], ["Why Complex", "#candidates"], ["Training", "#training"], ["Driver Assessments", "#"], ["CPC Training", "#"]]} /><div><h4 className="mb-6 mt-0 text-[10px] tracking-[.14em] text-[#8f9aa1]">Contact</h4><a className="mb-[14px] block text-xs" href="tel:02039237888">0203 923 7888</a><a className="mb-[14px] block text-xs" href="mailto:info@complexrecruitment.co.uk">info@complexrecruitment.co.uk</a><p className="max-w-[300px] text-xs leading-[1.6] text-[#8f9aa1]">Unit 2 Georgiou Business Park,<br />Second Avenue, London, N18 2PG</p></div></Container><Container className="mt-[70px] flex justify-between border-t border-white/15 pt-6 text-[9px] tracking-[.1em] text-[#758088] max-[760px]:block max-[760px]:leading-loose [&_span]:max-[760px]:block"><span>© 2026 Complex Recruitment</span><span>Privacy · Cookies · Terms · Modern Slavery</span><span>REC MEMBER</span></Container></footer>; }
function HomeGroup({ title, links }: { title: string; links: readonly (readonly [string, string])[] }) { return <div><h4 className="mb-6 mt-0 text-[10px] tracking-[.14em] text-[#8f9aa1]">{title}</h4>{links.map(([label, href], index) => <a className="mb-[14px] block text-xs outline-none hover:text-brand-red focus-visible:ring-2 focus-visible:ring-brand-red" key={`${label}-${index}`} href={href}>{label}</a>)}</div>; }
