import { Header } from '../../components/Header';
import { SectionLabel } from '../../components/SectionLabel';

const values=[['C','Collaborative','Working in partnership with clients.'],['O','Ownership','Taking responsibility for bookings, vacancies and requirements.'],['M','Mindful','Matching the right people while respecting deadlines and context.'],['P','Passionate','Bringing energy to every stage of recruitment.'],['L','Leading','Setting the standard through the way the team works.'],['EX','eXceed','Aiming to go beyond the expected.']];

export default function AboutPage(){return <main className="aboutPage">
  <section className="aboutHero"><Header active="About" theme="dark"/><div className="aboutHeroMedia"/><div className="aboutHeroShade"/><div className="pageShell aboutHeroGrid"><div><div className="eyebrow">ABOUT COMPLEX <span>/ PEOPLE & OPERATIONS</span></div><h1>Recruitment built<br/><em>around people.</em></h1></div><div className="aboutHeroAside"><p>Specialist recruitment across Driving, Industrial and Construction, combining experienced consultants, practical service models and a belief that the right people make operations work.</p><a className="button buttonAccent" href="/contact">Talk to Complex <span>↗</span></a></div></div><div className="aboutHeroStrip"><div className="pageShell"><b>London</b><b>Greater London</b><b>Essex</b><b>Surrey</b><b>Kent</b></div></div></section>

  <section className="aboutStory whiteSurface"><div className="pageShell aboutStoryGrid"><div><SectionLabel>WHO WE ARE</SectionLabel><h2>Specialist knowledge.<br/><em>Human service.</em></h2></div><div><p>Complex Recruitment provides temporary, ad-hoc and permanent staffing across Driving, Industrial and Construction. The company combines traditional and modern recruitment methods with dedicated sector consultants and compliance management tailored to industry requirements.</p><p>The current brand story consistently places staff and people at the heart of the business. This redesign makes that idea visible rather than leaving it buried in copy.</p></div></div></section>

  <section className="aboutNumbers softSurface"><div className="pageShell aboutNumbersGrid"><article><strong>03</strong><span>Specialist divisions</span></article><article><strong>24/7</strong><span>Operational support</span></article><article><strong>40+</strong><span>Years combined senior-management experience</span></article><article><strong>05</strong><span>Core coverage areas</span></article></div></section>

  <section className="aboutPeople"><div className="aboutPeopleImage"/><div className="aboutPeopleCopy"><SectionLabel>PEOPLE AT THE HEART</SectionLabel><h2>The business is built<br/><em>on relationships.</em></h2><p>Complex’s existing positioning speaks about collaboration, service, ethics and community. For the new site, the story is less about corporate slogans and more about what those principles look like in practice: ownership of client requirements, communication with workers and responsiveness when operations change.</p><a className="candidateTextLink darkLink" href="/employers">How We Support Employers <span>↗</span></a></div></section>

  <section className="aboutValues darkSurface"><div className="pageShell aboutValuesHead"><SectionLabel>THE COMPLEX VALUES</SectionLabel><div><h2>A name with<br/><em>meaning behind it.</em></h2><p>The current site builds its values around the letters in COMPLEX. We can retain that recognisable idea while simplifying the presentation and language.</p></div></div><div className="pageShell aboutValueGrid">{values.map(([l,t,c])=><article key={l}><span>{l}</span><h3>{t}</h3><p>{c}</p><i>↗</i></article>)}</div></section>

  <section className="aboutSectors whiteSurface"><div className="pageShell aboutSectorsHead"><SectionLabel>WHAT WE KNOW</SectionLabel><h2>Three specialist sectors.<br/><em>One Complex standard.</em></h2></div><div className="aboutSectorGrid"><a href="/sectors/driving" className="driving"><span>01</span><h3>Driving</h3><i>↗</i></a><a href="/sectors/industrial" className="industrial"><span>02</span><h3>Industrial</h3><i>↗</i></a><a href="/sectors/construction" className="construction"><span>03</span><h3>Construction</h3><i>↗</i></a></div></section>

  <section className="aboutFinal redSurface"><div className="pageShell aboutFinalGrid"><div><SectionLabel>START A CONVERSATION</SectionLabel><h2>Staff, work or simply<br/><em>a question?</em></h2></div><div><p>Whether you are building a workforce or looking for your next opportunity, start with the team that knows the sector.</p><div className="aboutFinalActions"><a className="button buttonDark" href="/request-staff">Request Staff <span>↗</span></a><a className="textLink" href="/jobs">Find Work →</a></div></div></div></section>
  <Footer />
</main>}
function Footer(){return <footer className="siteFooter"><img className="footerMark" src="/complex-mark.png" alt=""/><div className="pageShell footerLead"><div className="footerBrand"><img className="footerLogo" src="/complex-logo-white.png" alt="Complex Recruitment"/><p>Specialist workforce solutions across Driving, Industrial and Construction.</p></div><a className="footerCall" href="tel:02039237888"><span>CALL COMPLEX</span><strong>0203 923 7888</strong><i>↗</i></a></div><div className="pageShell footerNav"><div><h4>EMPLOYERS</h4><a href="/employers">Employer Solutions</a><a href="/request-staff">Request Staff</a></div><div><h4>CANDIDATES</h4><a href="/jobs">Find Jobs</a><a href="/candidates">Why Complex</a></div><div><h4>SECTORS</h4><a href="/sectors/driving">Driving</a><a href="/sectors/industrial">Industrial</a><a href="/sectors/construction">Construction</a></div><div><h4>COMPANY</h4><a href="/about">About</a><a href="/contact">Contact</a></div></div><div className="pageShell footerBottom"><span>© 2026 COMPLEX RECRUITMENT</span><nav><a href="/privacy">Privacy</a><a href="/cookies">Cookies</a><a href="/terms">Terms</a></nav></div></footer>}
