import { ConstructionRoleExplorer } from '../../../components/ConstructionRoleExplorer';
import { Footer } from '../../../components/layout/Footer';
import { SectorHero } from '../../../components/sectors/SectorHero';
import { SectorCompliance, SectorDualCta, SectorIntro, SectorJobs, SectorProcess, SectorRoles, SectorService } from '../../../components/sectors/SectorSections';

const serviceItems = ['Daily check-in confirmation','Management of rotas','Weekly onsite staff welfare sessions','Training workshops','Weekly management information','Monthly compliance log','Worker performance reviews','Buddy system'];

export default function ConstructionPage() {
  return <main className="bg-white text-ink">
    <SectorHero compactTitle sector="Construction & Engineering" title={<>Construction staffing built for<br/><em>the demands of site.</em></>} description="Temporary and permanent labour across main build, residential development, civil engineering and specialist construction environments." requestLabel="Request Construction Staff" jobsLabel="Find Construction Work" jobsHref="#construction-jobs" proofLabel="URGENT REQUIREMENTS" proofCopy="Prompt support for same- and next-day construction staffing needs." rail={['Labour & Trades','Plant Operators','Site Operatives','Temporary','Permanent']} images={['https://images.pexels.com/photos/1216589/pexels-photo-1216589.jpeg?auto=compress&cs=tinysrgb&w=2200','https://images.pexels.com/photos/6474475/pexels-photo-6474475.jpeg?auto=compress&cs=tinysrgb&w=2200']} positions={['center 48%','center 44%']} />
    <SectorIntro label="WHY COMPLEX CONSTRUCTION" title={<>Site-ready recruitment<br/><em>without the guesswork.</em></>} copy="Complex Construction supports public-sector bodies, consultancies, contractors and specialist subcontractors with labour across changing project programmes, urgent site requirements and permanent recruitment." proof={[["01","Urgent labour","Same- and next-day requirements supported where possible."],["02","Temporary & Permanent","Flexible supply across changing project and workforce needs."],["03","Industry checks","Required qualifications and vetting aligned to the client and site."],["04","Dedicated support","Responsive account management throughout the requirement."]]} />
    <SectorRoles label="CONSTRUCTION JOB CATEGORIES" title={<>From skilled trades<br/><em>to plant and site teams.</em></>} copy="Explore the labour, trade, plant and site-support categories Complex recruits across construction projects."><ConstructionRoleExplorer /></SectorRoles>
    <SectorCompliance image="https://images.pexels.com/photos/159306/construction-site-build-construction-work-159306.jpeg?auto=compress&cs=tinysrgb&w=1800" label="SITE COMPLIANCE" title={<>Right qualification.<br/><em>Right documentation.</em><br/>Site ready.</>} copy="Where projects have industry-specific vetting or qualification requirements, Complex supports the documentation and checks needed to help workers start compliantly and on time." checks={['Role and project requirement confirmed before sourcing','Relevant qualification and documentation checks','Eligibility and previous-work screening where required','Site and role expectations communicated before start','Assignment information and reporting procedures confirmed','Ongoing performance, welfare and service support']} button="Request Site-Ready Staff" />
    <SectorService title={<>Support across<br/><em>the project.</em></>} copy="Complex’s construction service model combines staffing with ongoing workforce and account support." items={serviceItems} />
    <SectorProcess label="FROM REQUIREMENT TO SITE" title={<>Built around the pace<br/><em>of construction.</em></>} steps={[["01","Brief us","Trade, qualification, site, numbers and start date."],["02","Source & verify","Suitable workers are matched and required documentation is checked."],["03","Confirm & mobilise","Workers receive assignment details and are prepared for site."],["04","Stay involved","Complex supports attendance, welfare, performance and service information."]]} />
    <SectorJobs id="construction-jobs" label="CONSTRUCTION OPPORTUNITIES" title={<>Current roles<br/><em>on site.</em></>} copy="Live roles will be pulled from the new jobs CMS and filtered automatically to the Construction division." jobs={[["CSCS Labourer","London","Construction","Temporary","CMS PREVIEW"],["Telehandler Operator","Greater London","Construction","Temporary","CMS PREVIEW"],["Site Supervisor","London","Construction","Permanent","CMS PREVIEW"]]} />
    <SectorDualCta employer={{ label:'FOR EMPLOYERS', title:'I need construction staff.', copy:'Tell us the trade, project, numbers and timing. We’ll take it from there.', action:'Request Staff', href:'/request-staff' }} candidate={{ label:'FOR CANDIDATES', title:'I’m looking for construction work.', copy:'Explore current labour, trade and site opportunities.', action:'Find Construction Jobs', href:'/jobs' }} />
    <Footer />
  </main>;
}
