import { Header } from '../../components/Header';
import { SectionLabel } from '../../components/SectionLabel';
import { RegisterInterestForm } from '../../components/RegisterInterestForm';

export default function RegisterInterestPage(){
  return <main className="interestPage">
    <section className="interestHero"><Header active="Candidates" theme="light"/><div className="pageShell interestHeroGrid"><div><div className="candidateEyebrow">FOR CANDIDATES <span>/ REGISTER INTEREST</span></div><h1>Nothing quite right?<br/><em>Stay on our radar<span className="accentPeriod">.</span></em></h1></div><div><p>Tell us what kind of work you’re looking for and how to reach you. If a relevant opportunity comes up, the Complex team has a way to find you.</p><a className="candidateTextLink darkLink" href="/jobs">Browse live jobs <span>↗</span></a></div></div><div className="interestHeroImage" aria-hidden="true"/></section>
    <section className="interestMain"><div className="pageShell interestLayout"><aside><SectionLabel>QUICK PROFILE</SectionLabel><h2>Two steps.<br/><em>One useful introduction.</em></h2><p>This isn’t a full job application. It simply gives the recruitment team enough information to understand what might suit you.</p><div className="interestBenefits"><span>Driving · Industrial · Construction</span><span>Temporary or permanent work</span><span>CV upload optional at first draft stage</span></div></aside><RegisterInterestForm/></div></section>
    <section className="interestNext"><div className="pageShell interestNextGrid"><div><SectionLabel>WHEN YOU REGISTER</SectionLabel><h2>We keep the next<br/><em>step human.</em></h2></div><p>Registering interest does not guarantee a placement. It simply creates a candidate profile that the recruitment team can use when relevant opportunities arise. Final data-retention and privacy wording will be confirmed before launch.</p></div></section>
    <footer className="siteFooter"><img className="footerMark" src="/complex-mark.png" alt=""/><div className="pageShell footerLead"><div className="footerBrand"><img className="footerLogo" src="/complex-logo-white.png" alt="Complex Recruitment"/><p>Specialist workforce solutions across Driving, Industrial and Construction.</p></div><a className="footerCall" href="tel:02039237888"><span>CALL COMPLEX</span><strong>0203 923 7888</strong><i>↗</i></a></div><div className="pageShell footerBottom"><span>© 2026 COMPLEX RECRUITMENT</span><nav><a href="/privacy">Privacy</a><a href="/cookies">Cookies</a><a href="/terms">Terms</a><a href="/modern-slavery">Modern Slavery</a></nav></div></footer>
  </main>
}
