import { Footer } from '../../../components/layout/Footer';
import { Container } from '../../../components/layout/Container';
import { SectionLabel } from '../../../components/SectionLabel';
import { ServiceHero } from '../../../components/training/ServiceHero';
import { ButtonLink } from '../../../components/ui/ButtonLink';
import { TextLink } from '../../../components/ui/TextLink';

const modules = [['01', 'A', 'Theory', 'Knowledge and understanding relevant to professional driving and safe road use.'], ['02', 'B', 'Practical', 'On-road and vehicle-based assessment focused on driving behaviour, control and judgement.'], ['03', 'C', 'Load Securing', 'Practical awareness around safe loading, restraint and operational responsibility.']];
const steps = [['01', 'Brief us', 'Tell us the driver group, vehicle context and what you need to understand.'], ['02', 'Assess', 'Complex carries out the agreed theory, practical and/or load-security assessment.'], ['03', 'Report', 'Receive clear feedback and recommendations from the assessment.'], ['04', 'Develop', 'Discuss refresher training, follow-up assessment or further support where needed.']];

export default function DriverAssessmentsPage() {
  return <main>
    <ServiceHero kind="assessment" eyebrow={<>DRIVER ASSESSMENTS <span className="ml-[10px] text-[#b5b8ba] max-[640px]:hidden">/ COMPLEX DRIVING</span></>} title={<>Know the driver.<br /><em>Before the road does.</em></>} intro="Practical, theory-led and load-security assessment designed to give employers useful insight into driver capability, safety and development needs." actionHref="#assessment-enquiry" actionLabel="Book an Assessment" badgeLabel="ASSESSMENT FOCUS" badgeValue="03" badgeCopy="Theory · Practical · Load securing" railItems={['Theory Test', 'Practical Assessment', 'Load Securing', 'Actionable Reports']} />

    <section className="bg-white py-[126px] max-[640px]:py-[88px]"><Container className="grid grid-cols-[1fr_.7fr] items-end gap-[100px] max-[1000px]:grid-cols-1 max-[1000px]:gap-[46px]"><div><SectionLabel>ASSESS WITH PURPOSE</SectionLabel><h2 className="m-0 mt-[34px] text-[clamp(50px,5vw,82px)] leading-[.95] tracking-[-.055em] max-[640px]:text-5xl">More useful than<br /><em className="not-italic text-brand-red">a simple pass or fail.</em></h2></div><div><p className="mb-7 max-w-[590px] text-[15px] leading-[1.72] text-[#626e74]">Complex positions assessments as a practical way to understand how a driver performs, where risk may sit and where development could help. The aim is to give both the employer and driver something useful to act on.</p><TextLink href="#assessment-enquiry">Discuss Your Requirement</TextLink></div></Container></section>

    <section className="bg-surface py-[126px] max-[640px]:py-[88px]"><Container><div className="grid grid-cols-[.4fr_1fr] gap-[70px] max-[640px]:block"><SectionLabel>WHAT WE ASSESS</SectionLabel><h2 className="m-0 max-[640px]:mt-7 text-[clamp(50px,5vw,82px)] leading-[.95] tracking-[-.055em]">Three perspectives.<br /><em className="not-italic text-brand-red">One clearer picture.</em></h2></div><div className="mt-[70px] grid grid-cols-3 border-l border-t border-line max-[1000px]:grid-cols-2 max-[640px]:grid-cols-1">{modules.map(([number, icon, title, copy]) => <article key={number} className="group min-h-[390px] border-b border-r border-line p-7 transition-colors hover:bg-white focus-within:bg-white max-[640px]:min-h-[300px]"><div className="transition-transform duration-500 ease-complex group-hover:translate-x-2"><span className="text-[8px] font-extrabold text-brand-red">{number}</span><div className="mt-[70px] grid h-12 w-12 place-items-center border border-line text-xs font-extrabold">{icon}</div><h3 className="mb-[14px] mt-8 text-[30px] tracking-[-.04em]">{title}</h3><p className="max-w-[310px] text-xs leading-[1.65] text-[#677278]">{copy}</p></div></article>)}</div></Container></section>

    <section className="grid grid-cols-2 bg-brand-grey text-white max-[1000px]:grid-cols-1"><div className="min-h-[640px] bg-[linear-gradient(rgba(17,18,20,.05),rgba(17,18,20,.2)),url('https://images.pexels.com/photos/3760067/pexels-photo-3760067.jpeg?auto=compress&cs=tinysrgb&w=1800')] bg-cover bg-center grayscale-[.25] max-[1000px]:min-h-[430px]" /><div className="px-[max(60px,calc((100vw-1400px)/2))] pb-[100px] pl-20 pt-[110px] max-[640px]:px-6 max-[640px]:py-[68px] [&_.sectionLabel]:text-white"><SectionLabel>REPORTING &amp; RECOMMENDATIONS</SectionLabel><h2 className="m-0 mt-[34px] text-[clamp(50px,5vw,82px)] leading-[.95] tracking-[-.055em] max-[640px]:text-5xl">Turn observations<br /><em className="not-italic text-brand-red">into action.</em></h2><p className="my-7 max-w-[600px] text-[15px] leading-[1.7] text-white/80">Assessment findings should not disappear into a checkbox. Complex’s current service describes detailed, actionable recommendations designed to highlight areas needing attention while recognising existing strengths.</p><div className="flex flex-wrap gap-2">{['Clear observations', 'Targeted recommendations', 'Development priorities', 'Follow-up support'].map(item => <span key={item} className="border border-white/20 px-[13px] py-[11px] text-[9px]">{item}</span>)}</div></div></section>

    <section className="bg-white py-[126px] max-[640px]:py-[88px]"><Container><div className="grid grid-cols-[.4fr_1fr] gap-[70px] max-[640px]:block"><SectionLabel>HOW IT WORKS</SectionLabel><h2 className="m-0 max-[640px]:mt-7 text-[clamp(50px,5vw,82px)] leading-[.95] tracking-[-.055em]">Simple to arrange.<br /><em className="not-italic text-brand-red">Useful to act on.</em></h2></div><div className="mt-[70px] grid grid-cols-4 border-l border-t border-line max-[1000px]:grid-cols-2 max-[640px]:grid-cols-1">{steps.map(([number, title, copy]) => <article key={number} className="group relative min-h-[300px] overflow-hidden border-b border-r border-line p-[27px] transition-colors before:absolute before:left-0 before:right-full before:top-0 before:h-[3px] before:bg-brand-red before:transition-[right] before:duration-300 hover:bg-surface hover:before:right-0"><span className="text-[8px] font-extrabold text-brand-red">{number}</span><h3 className="mb-[14px] mt-[86px] text-2xl">{title}</h3><p className="max-w-[260px] text-[11px] leading-[1.6] text-[#68747a]">{copy}</p></article>)}</div></Container></section>

    <section className="bg-ink py-[126px] text-white max-[640px]:py-[88px]" id="assessment-enquiry"><Container className="grid grid-cols-[1fr_.78fr] items-center gap-[100px] max-[1000px]:grid-cols-1 max-[1000px]:gap-[46px]"><div className="[&_.sectionLabel]:text-white"><SectionLabel>START AN ASSESSMENT</SectionLabel><h2 className="m-0 mt-[34px] text-[clamp(50px,5vw,82px)] leading-[.95] tracking-[-.055em] max-[640px]:text-5xl">Tell us what you<br /><em className="not-italic text-brand-red">need to understand.</em></h2></div><div className="min-h-[330px] bg-white px-[46px] py-[42px] text-ink max-[640px]:px-6"><span className="text-[8px] font-extrabold tracking-[.17em] text-[#7b858b]">DRIVER ASSESSMENT ENQUIRY</span><h3 className="mb-4 mt-[45px] text-[34px] leading-[1.05] tracking-[-.04em]">Employer or individual driver?</h3><p className="mb-7 text-[13px] leading-[1.65] text-[#667278]">Share the type of assessment, approximate number of drivers and preferred timing. The Complex team can confirm the most suitable next step.</p><ButtonLink href="/contact">Make an Enquiry</ButtonLink></div></Container></section>
    <Footer variant="training" />
  </main>;
}
