// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/candidates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidates">> = Specific
  const handler = {} as typeof import("../../app/candidates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/compliance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compliance">> = Specific
  const handler = {} as typeof import("../../app/compliance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cookies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cookies">> = Specific
  const handler = {} as typeof import("../../app/cookies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/employers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employers">> = Specific
  const handler = {} as typeof import("../../app/employers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/employers/permanent-recruitment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employers/permanent-recruitment">> = Specific
  const handler = {} as typeof import("../../app/employers/permanent-recruitment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/jobs/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jobs/[slug]">> = Specific
  const handler = {} as typeof import("../../app/jobs/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/jobs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jobs">> = Specific
  const handler = {} as typeof import("../../app/jobs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/modern-slavery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modern-slavery">> = Specific
  const handler = {} as typeof import("../../app/modern-slavery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/register-interest/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register-interest">> = Specific
  const handler = {} as typeof import("../../app/register-interest/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/request-staff/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/request-staff">> = Specific
  const handler = {} as typeof import("../../app/request-staff/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sectors/business-operational-support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sectors/business-operational-support">> = Specific
  const handler = {} as typeof import("../../app/sectors/business-operational-support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sectors/construction/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sectors/construction">> = Specific
  const handler = {} as typeof import("../../app/sectors/construction/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sectors/driving/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sectors/driving">> = Specific
  const handler = {} as typeof import("../../app/sectors/driving/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sectors/industrial/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sectors/industrial">> = Specific
  const handler = {} as typeof import("../../app/sectors/industrial/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sectors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sectors">> = Specific
  const handler = {} as typeof import("../../app/sectors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/tailwind-check/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tailwind-check">> = Specific
  const handler = {} as typeof import("../../app/tailwind-check/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/training/cpc/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/training/cpc">> = Specific
  const handler = {} as typeof import("../../app/training/cpc/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/training/driver-assessments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/training/driver-assessments">> = Specific
  const handler = {} as typeof import("../../app/training/driver-assessments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/training/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/training">> = Specific
  const handler = {} as typeof import("../../app/training/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
