import { HeroEyebrow } from '../../components/HeroEyebrow';
import { CandidateOpportunities } from '../../components/CandidateOpportunities';
import { Header } from '../../components/Header';
import { SectionLabel } from '../../components/SectionLabel';
import { Container } from '../../components/layout/Container';
import { Footer } from '../../components/layout/Footer';
import { RegisterInterestForm } from '../../components/RegisterInterestForm';
import { ArrowIcon } from '../../components/ui/ArrowIcon';
import { ButtonLink } from '../../components/ui/ButtonLink';
import { TextLink } from '../../components/ui/TextLink';

const benefits=[['01','Weekly PAYE pay','Temporary workers are engaged through PAYE, with dependable weekly pay.'],['02','Portal & timesheets','Use the candidate portal to access and manage relevant timesheet information.'],['03','Flexible opportunities','Temporary work, ongoing assignments, temp-to-perm opportunities and permanent roles.'],['04','Real communication','A recruitment team you can reach when you need an update or support.'],['05','Refer a friend','Introduce someone suitable through the Complex refer-a-friend scheme.'],['06','Sector specialists','People who understand the operational environments they recruit for.']];
const sectorCards=[
  {n:'01',title:'Driving & Transport',slug:'driving',copy:'HGV Class 1 & 2, 7.5T, 3.5T, ADR, HIAB and transport roles.',image:'https://images.pexels.com/photos/35501718/pexels-photo-35501718/free-photo-of-aerial-view-of-industrial-truck-parking-lot.jpeg?auto=compress&cs=tinysrgb&w=1800'},
  {n:'02',title:'Industrial & Warehouse',slug:'industrial',copy:'Warehouse, FLT, picking, loading, production and supervisory opportunities.',image:'https://images.pexels.com/photos/6169178/pexels-photo-6169178.jpeg?auto=compress&cs=tinysrgb&w=1800'},
  {n:'03',title:'Construction & Engineering',slug:'construction',copy:'Trades, plant, site operations, labour and project-based opportunities.',image:'https://images.pexels.com/photos/8138734/pexels-photo-8138734.jpeg?auto=compress&cs=tinysrgb&w=1800'},
  {n:'04',title:'Business & Operational Support',slug:'business-operational-support',copy:'Planning, administration, coordination, customer service and supervisory opportunities.',image:'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=1800'},
];
const heading='section-heading text-[clamp(52px,5vw,82px)] leading-[.95] tracking-[-.055em] max-[760px]:text-5xl';

export default function CandidatesPage(){return <main className="bg-white text-ink">
  <section id="top" className="relative isolate grid grid-rows-[92px_clamp(400px,40vh,480px)] overflow-hidden bg-ink text-white max-[900px]:grid-rows-[92px_auto] max-[760px]:grid-rows-[76px_auto]">
    <div className="absolute inset-y-0 right-0 -z-[2] w-[54%] [mask-image:linear-gradient(90deg,transparent,black_32%)] bg-[url('https://images.pexels.com/photos/4481326/pexels-photo-4481326.jpeg?auto=compress&cs=tinysrgb&w=1600')] bg-cover bg-center grayscale-[.3] max-[900px]:w-full max-[900px]:opacity-45" />
    <div className="absolute inset-0 -z-[1] bg-[linear-gradient(90deg,rgba(17,18,20,1)_0%,rgba(17,18,20,.96)_43%,rgba(17,18,20,.28)_74%,rgba(17,18,20,.52))]" />
    <Header active="Candidates" theme="dark"/>
    <Container gutter="wide" className="grid grid-cols-[minmax(0,1fr)_285px] items-center gap-12 py-8 max-[900px]:grid-cols-1 max-[900px]:py-[61px] max-[760px]:py-[52px] max-[760px]:pb-[52px]">
      <div><HeroEyebrow detail="FIND WORK">FOR CANDIDATES</HeroEyebrow><h1 className="m-0 min-[1101px]:w-[calc(100%+333px)] text-[clamp(58px,5.2vw,82px)] font-semibold leading-[.95] tracking-[-.065em] max-[1100px]:text-[68px] max-[1100px]:leading-[.88] max-[760px]:text-[clamp(48px,13vw,60px)]">Find work that works for you<span className="text-brand-red">.</span></h1><p className="my-7 max-w-[620px] text-base leading-[1.65] text-white/75 max-[760px]:my-6 max-[760px]:text-sm">Explore current opportunities across our four specialist sectors, with a recruitment team that keeps communication clear from application to first shift.</p><div className="flex items-center gap-7 max-[520px]:items-start max-[520px]:flex-col"><ButtonLink href="/jobs">Find Jobs</ButtonLink><TextLink href="#register-interest" variant="light" arrowDirection="down-right">Register your interest</TextLink></div></div>
      <aside className="relative mb-1 self-end border-l-2 border-brand-red bg-ink/40 p-5 backdrop-blur-lg max-[900px]:w-[285px]"><span className="text-[8px] tracking-[.16em] text-white/60">CURRENT OPPORTUNITIES</span><strong className="mt-5 block text-xl leading-[1.2]">Four specialist sectors</strong><ArrowIcon className="absolute right-5 top-5 text-brand-red"/></aside>
    </Container>

  </section>

  <section aria-label="Candidate benefits" className="bg-surface pt-6"><Container className="grid grid-cols-4 gap-3 max-[900px]:grid-cols-2 max-[430px]:grid-cols-1">{['Weekly PAYE pay','Candidate portal','Flexible roles','Real support'].map((title,index)=><div key={title} className="flex min-h-[88px] items-center gap-4 border border-line bg-white px-5 py-5"><span className="text-[9px] font-bold text-brand-red">0{index+1}</span><strong className="text-sm tracking-[-.015em]">{title}</strong></div>)}</Container></section>
  <CandidateOpportunities />
  <section className="py-[126px] max-[760px]:py-[90px]"><Container><div className="mb-[70px] grid grid-cols-[.43fr_1fr] gap-[72px] max-[1100px]:grid-cols-[.32fr_1fr] max-[760px]:block max-[760px]:mb-12"><SectionLabel>WHY WORK WITH COMPLEX</SectionLabel><div className="max-[760px]:mt-[30px]"><h2 className={`${heading} m-0`}>Good work starts<br/><em className="not-italic text-brand-red">with being valued.</em></h2><p className="mt-[26px] max-w-[650px] text-[15px] leading-[1.7] text-muted">We want the experience around the job to feel as dependable as the job itself — clear communication, reliable processes and people who understand the sectors they recruit for.</p></div></div><div className="candidateBenefits grid min-h-[610px] grid-cols-[.44fr_.56fr] gap-7 max-[1100px]:gap-[22px] max-[1100px]:grid-cols-[.4fr_.6fr] max-[760px]:grid-cols-1"><div className="relative min-h-[610px] bg-[linear-gradient(rgba(17,18,20,.02),rgba(17,18,20,.22)),url('https://images.pexels.com/photos/4481326/pexels-photo-4481326.jpeg?auto=compress&cs=tinysrgb&w=1800')] bg-cover bg-center grayscale-[.14] max-[760px]:min-h-[390px]"><div className="absolute inset-x-7 bottom-7 border border-white/50 bg-white/90 p-6 backdrop-blur-lg"><span className="mb-3 block text-[8px] font-extrabold tracking-[.17em] text-brand-red">PEOPLE FIRST</span><strong className="text-xl leading-[1.22]">Clear communication.<br/>Real support.</strong></div></div><div className="flex min-w-0 flex-col"><div className="grid flex-1 grid-cols-2 border-l border-t border-line bg-surface max-[760px]:grid-cols-1">{benefits.map(([n,t,c])=><article key={n} className="group grid min-h-0 grid-cols-[32px_1fr_20px] items-center gap-3 border-b border-r border-line px-6 py-[22px] transition-colors hover:bg-white max-[760px]:min-h-[130px] max-[760px]:border-r-0"><span className="self-start pt-1 text-[8px] font-bold text-brand-red">{n}</span><div><h3 className="mb-[7px] text-lg">{t}</h3><p className="max-w-[260px] text-[10.5px] leading-[1.52] text-muted">{c}</p></div><ArrowIcon className="-translate-x-2 translate-y-2 text-brand-red opacity-0 transition group-hover:translate-x-0 group-hover:translate-y-0 group-hover:opacity-100"/></article>)}</div></div></div></Container></section>
  <section className="bg-[#151618] py-[126px] text-white max-[760px]:py-[90px]"><Container><div className="grid grid-cols-[1fr_.65fr] items-end gap-[110px] max-[760px]:grid-cols-1 max-[760px]:gap-8"><div><SectionLabel>YOUR JOURNEY</SectionLabel><h2 className={`${heading} mt-[38px]`}>From application<br/><em className="not-italic text-brand-red">to first shift.</em></h2></div><p className="max-w-[520px] text-[15px] leading-[1.65] text-white/65">A straightforward recruitment journey, with clear communication at each stage and role-specific checks where required.</p></div><div className="mt-[78px] grid grid-cols-4 border-y border-white/15 max-[760px]:mt-[55px] max-[760px]:grid-cols-1">{[['01','Find a role','Browse live vacancies and choose an opportunity that fits your experience.'],['02','Apply','Send the essentials and your CV through a quick, mobile-friendly application.'],['03','Talk to Complex','We review your application, discuss the role and confirm any checks required.'],['04','Get ready','If the role is right, we help you understand what you need before the assignment starts.']].map(([n,t,c])=><article key={n} className="group relative min-h-[330px] border-r border-white/15 p-7 transition-colors before:absolute before:inset-x-0 before:top-0 before:h-[3px] before:origin-left before:scale-x-0 before:bg-brand-red before:transition-transform hover:bg-white/5 hover:before:scale-x-100 max-[760px]:min-h-[230px] max-[760px]:border-b max-[760px]:border-r-0"><span className="text-[9px] text-white/45">{n}</span><h3 className="mb-4 mt-[72px] text-2xl max-[760px]:mt-[42px]">{t}</h3><p className="max-w-[235px] text-xs leading-[1.65] text-white/60">{c}</p><ArrowIcon className="absolute bottom-[25px] right-[25px] text-brand-red transition-transform group-hover:translate-x-1.5 group-hover:-translate-y-1.5"/></article>)}</div></Container></section>
  <section className="py-[126px] max-[760px]:py-[90px]"><Container><div className="grid grid-cols-[.45fr_1fr] items-end gap-[70px] max-[760px]:block"><SectionLabel>WHERE WE RECRUIT</SectionLabel><h2 className={`${heading} m-0 max-[760px]:mt-[30px]`}>Specialist opportunities<br/>across four sectors.</h2></div><div className="mt-[70px] grid grid-cols-2 gap-[14px] max-[760px]:mt-12 max-[760px]:grid-cols-1">{sectorCards.map((sector)=><a href={`/sectors/${sector.slug}`} key={sector.n} className="group relative isolate min-h-[540px] overflow-hidden bg-ink text-white outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-brand-red max-[1100px]:min-h-[490px] max-[760px]:min-h-[430px]"><div className="absolute -inset-[2%] -z-[3] scale-[1.02] bg-cover bg-center grayscale-[.45] transition duration-700 ease-complex group-hover:scale-[1.075] group-hover:grayscale-0 group-focus-visible:scale-[1.075] group-focus-visible:grayscale-0" style={{backgroundImage:`url('${sector.image}')`}}/><div className="absolute inset-0 -z-[2] bg-[linear-gradient(180deg,rgba(10,11,12,.12),rgba(10,11,12,.28)_48%,rgba(10,11,12,.86))]"/><div className="absolute inset-x-0 bottom-0 -z-[1] h-[62%] translate-y-full bg-[linear-gradient(180deg,transparent,rgba(236,33,37,.38)_35%,rgba(236,33,37,.92))] transition-transform duration-700 group-hover:translate-y-0 group-focus-visible:translate-y-0 max-[760px]:translate-y-0"/><span className="absolute left-[27px] top-[26px] text-[9px] text-white/70">{sector.n}</span><div className="absolute bottom-[30px] left-7 right-[70px] transition-transform group-hover:-translate-y-2 group-focus-visible:-translate-y-2"><small className="mb-3 block translate-y-[10px] text-[8px] font-bold tracking-[.17em] text-white/70 opacity-0 transition group-hover:translate-y-0 group-hover:opacity-100 group-focus-visible:translate-y-0 group-focus-visible:opacity-100 max-[760px]:translate-y-0 max-[760px]:opacity-100">EXPLORE SECTOR</small><strong className="block text-[47px] leading-[.95] tracking-[-.05em] max-[1100px]:text-[39px] max-[760px]:text-[40px]">{sector.title}</strong><p className="mt-4 max-w-[330px] text-[11px] leading-[1.55] text-white/75">{sector.copy}</p></div><ArrowIcon className="absolute bottom-[30px] right-7 text-[23px] transition-transform group-hover:translate-x-2 group-hover:-translate-y-2"/></a>)}</div></Container></section>
  <section className="bg-[#eceeef] py-[126px] max-[760px]:py-[90px]"><Container className="grid grid-cols-[.8fr_1.2fr] items-start gap-[95px] max-[760px]:grid-cols-1 max-[760px]:gap-[50px]"><div><SectionLabel>TRAINING & DEVELOPMENT</SectionLabel><h2 className={`${heading} mt-[38px]`}>Keep moving<br/><em className="not-italic text-brand-red">forward.</em></h2><p className="my-7 max-w-[500px] text-[15px] leading-[1.7] text-muted">Complex also supports professional drivers through assessments, CPC training and relevant development opportunities.</p><ButtonLink href="/compliance" variant="dark">Explore Compliance &amp; Training</ButtonLink></div><div className="grid grid-cols-2 gap-[14px] max-[520px]:grid-cols-1">{[['01','Driver Assessments','Practical and theoretical evaluation designed around safer, more capable driving.','/training/driver-assessments'],['02','CPC Training','Professional driver training and development for a highly regulated sector.','/training/cpc']].map(([n,t,c,h])=><a href={h} key={n} className="group relative min-h-[360px] border border-line bg-white p-7 outline-none transition hover:-translate-y-[5px] hover:bg-brand-red hover:text-white focus-visible:ring-2 focus-visible:ring-brand-red max-[760px]:min-h-[280px]"><span className="text-[9px] text-brand-red group-hover:text-white/70">{n}</span><h3 className="mb-[18px] mt-[110px] text-[28px] leading-[1.05] tracking-[-.035em] max-[760px]:mt-[78px]">{t}</h3><p className="max-w-[290px] text-xs leading-[1.6] text-muted group-hover:text-white/75">{c}</p><ArrowIcon className="absolute right-[27px] top-[27px] text-[22px] transition-transform group-hover:translate-x-[7px] group-hover:-translate-y-[7px]"/></a>)}</div></Container></section>
  <section id="register-interest" className="scroll-mt-6 bg-surface py-[126px] max-[760px]:py-[90px]"><Container className="grid grid-cols-[.68fr_1.32fr] items-start gap-[90px] max-[1100px]:grid-cols-1 max-[1100px]:gap-[60px]"><aside className="max-[1100px]:max-w-[700px]"><SectionLabel>REGISTER YOUR INTEREST</SectionLabel><h2 className={`${heading} mt-[34px]`}>Can’t find<br/><em className="not-italic text-brand-red">the right role?</em></h2><p className="mt-7 max-w-[430px] text-sm leading-[1.72] text-muted">If nothing suitable is live right now, register your interest and our team can keep your details in mind for relevant opportunities.</p></aside><RegisterInterestForm/></Container></section>
  <section className="bg-brand-grey py-[126px] text-white max-[760px]:py-[90px]"><Container className="grid grid-cols-[.75fr_1.25fr] items-end gap-[100px] max-[760px]:grid-cols-1 max-[760px]:gap-12"><div><SectionLabel>CAN'T SEE THE RIGHT ROLE?</SectionLabel><h2 className={`${heading} mt-[34px]`}>Stay on our<br/><em className="not-italic text-brand-red">radar.</em></h2></div><div><p className="mb-7 max-w-[570px] text-[15px] leading-[1.7] text-white/75">Share your details and CV so the Complex team can contact you when a relevant opportunity comes up.</p><ButtonLink href="#register-interest">Register your interest</ButtonLink></div></Container></section>
  <Footer/>
</main>}
