import type { ReactNode } from 'react';
import { SectionLabel } from '../SectionLabel';
import { Container } from '../layout/Container';
import { ArrowIcon } from '../ui/ArrowIcon';
import { ButtonLink } from '../ui/ButtonLink';
import { TextLink } from '../ui/TextLink';

export type NumberedItem = readonly [string, string, string];
const heading = 'section-heading m-0 text-[clamp(50px,5.15vw,84px)] leading-[.94] tracking-[-.057em] max-[640px]:text-5xl [&_em]:not-italic [&_em]:text-brand-red';

export function SectorIntro({ label, title, copy, proof }: { label: string; title: ReactNode; copy: string; proof: readonly NumberedItem[] }) {
  return <section className="bg-white py-[130px] max-[640px]:py-[88px]"><Container><div className="grid grid-cols-[1fr_.7fr] items-end gap-[100px] max-[1180px]:gap-[60px] max-[920px]:grid-cols-1 max-[920px]:gap-[38px]"><div><SectionLabel>{label}</SectionLabel><h2 className={`${heading} mt-[38px]`}>{title}</h2></div><div><p className="mb-[30px] max-w-[600px] text-[15px] leading-[1.72] text-[#606c72]">{copy}</p><TextLink href="/employers">Explore Employer Solutions</TextLink></div></div><div className="mt-[82px] grid grid-cols-4 border-l border-t border-line max-[920px]:grid-cols-2 max-[640px]:grid-cols-1">{proof.map(([number, title, copy]) => <article key={number} className="group min-h-[270px] border-b border-r border-line p-7 transition-colors duration-300 hover:bg-surface max-[640px]:min-h-[215px]"><span className="text-[8px] font-extrabold text-brand-red">{number}</span><h3 className="mb-[15px] mt-[82px] text-[23px] leading-[1.05] tracking-[-.035em] transition-transform duration-300 ease-complex group-hover:translate-x-[7px] max-[640px]:mt-[54px]">{title}</h3><p className="max-w-[250px] text-[11px] leading-[1.62] text-[#69757a] transition-transform duration-300 ease-complex group-hover:translate-x-[7px]">{copy}</p></article>)}</div></Container></section>;
}

export function SectorRoles({ label, title, copy, children }: { label: string; title: ReactNode; copy: string; children: ReactNode }) {
  return <section className="bg-surface py-[126px] max-[640px]:py-[88px]"><Container><div className="grid grid-cols-[1fr_.62fr] items-end gap-[95px] max-[1180px]:grid-cols-[1fr_.7fr] max-[1180px]:gap-[60px] max-[920px]:grid-cols-1 max-[920px]:gap-[38px]"><div><SectionLabel>{label}</SectionLabel><h2 className={`${heading} mt-[38px]`}>{title}</h2></div><p className="m-0 max-w-[560px] text-[15px] leading-[1.7] text-[#606c72]">{copy}</p></div>{children}</Container></section>;
}

export function SectorCompliance({ image, label, title, copy, checks, button }: { image: string; label: string; title: ReactNode; copy: string; checks: readonly string[]; button: string }) {
  return <section className="grid min-h-[820px] grid-cols-2 bg-ink text-white max-[920px]:grid-cols-1"><div aria-hidden="true" className="min-h-[460px] bg-cover bg-center grayscale-[.2] max-[640px]:min-h-[330px]" style={{ backgroundImage: `linear-gradient(180deg,rgba(17,18,20,.03),rgba(17,18,20,.28)),url('${image}')` }} /><div className="py-[110px] pl-20 pr-[max(58px,calc((100vw-1400px)/2))] max-[1180px]:pl-[58px] max-[920px]:px-[50px] max-[920px]:py-20 max-[640px]:px-6 max-[640px]:py-[68px] [&_.sectionLabel]:text-white"><SectionLabel>{label}</SectionLabel><h2 className={`${heading} mt-[38px]`}>{title}</h2><p className="my-7 mb-10 max-w-[590px] text-[15px] leading-[1.7] text-[#aeb5b9]">{copy}</p><div className="mb-10 border-t border-white/15">{checks.map((item, index) => <div key={item} className="group grid min-h-[67px] grid-cols-[46px_1fr] items-center gap-[10px] border-b border-white/15 transition-colors duration-300 hover:bg-white/[.045]"><span className="text-[8px] text-brand-red transition-transform duration-300 group-hover:translate-x-3">{String(index + 1).padStart(2, '0')}</span><b className="text-xs font-semibold leading-[1.4] text-[#eef0f1] transition-transform duration-300 group-hover:translate-x-3">{item}</b></div>)}</div><ButtonLink href="/request-staff">{button}</ButtonLink></div></section>;
}

export function SectorService({ title, copy, items }: { title: ReactNode; copy: string; items: readonly string[] }) {
  return <section className="bg-white py-[126px] max-[640px]:py-[88px]"><Container className="grid grid-cols-[.62fr_1.38fr] gap-[90px] max-[1180px]:grid-cols-[.7fr_1.3fr] max-[1180px]:gap-[55px] max-[920px]:grid-cols-1 max-[920px]:gap-[38px]"><div><SectionLabel>SERVICE DELIVERY</SectionLabel><h2 className={`${heading} mt-[38px]`}>{title}</h2><p className="mt-7 max-w-[430px] text-sm leading-[1.7] text-[#646f75]">{copy}</p></div><div className="grid grid-cols-2 border-l border-t border-line max-[640px]:grid-cols-1">{items.map((item, index) => <article key={item} className="group relative min-h-[175px] border-b border-r border-line p-6 transition-colors duration-300 hover:bg-surface"><span className="text-[8px] font-extrabold text-brand-red">{String(index + 1).padStart(2, '0')}</span><h3 className="mb-0 mt-[62px] max-w-[220px] text-lg leading-[1.12] tracking-[-.025em] transition-transform duration-300 group-hover:translate-x-[7px]">{item}</h3><ArrowIcon className="absolute right-[22px] top-[22px] -translate-x-1.5 translate-y-1.5 text-brand-red opacity-0 transition duration-300 group-hover:translate-x-0 group-hover:translate-y-0 group-hover:opacity-100" /></article>)}</div></Container></section>;
}

export function SectorProcess({ label, title, steps }: { label: string; title: ReactNode; steps: readonly NumberedItem[] }) {
  return <section className="bg-surface py-[126px] max-[640px]:py-[88px]"><Container><div className="grid grid-cols-[.4fr_1fr] items-start gap-[70px] max-[1180px]:grid-cols-[.32fr_1fr] max-[1180px]:gap-[46px] max-[920px]:grid-cols-1 max-[920px]:gap-[38px]"><SectionLabel>{label}</SectionLabel><h2 className={heading}>{title}</h2></div><div className="mt-[72px] grid grid-cols-4 border-l border-t border-line max-[920px]:grid-cols-2 max-[640px]:grid-cols-1">{steps.map(([number, title, copy]) => <article key={number} className="group relative min-h-[315px] overflow-hidden border-b border-r border-line bg-white/30 p-[27px] transition-[background,transform] duration-300 ease-complex before:absolute before:inset-x-0 before:top-0 before:h-[3px] before:origin-left before:scale-x-0 before:bg-brand-red before:transition-transform before:duration-300 hover:-translate-y-[3px] hover:bg-white hover:before:scale-x-100 max-[640px]:min-h-[240px]"><span className="text-[8px] text-[#899196]">{number}</span><h3 className="mb-4 mt-[82px] text-[23px] tracking-[-.03em] max-[640px]:mt-[52px]">{title}</h3><p className="max-w-[230px] text-[11px] leading-[1.6] text-[#68747a]">{copy}</p></article>)}</div></Container></section>;
}

export type SectorJob = readonly [string, string, string, string, string];
export function SectorJobs({ id, label, title, copy, jobs }: { id: string; label: string; title: ReactNode; copy: string; jobs: readonly SectorJob[] }) {
  return <section id={id} className="bg-white py-[126px] max-[640px]:py-[88px]"><Container><div className="grid grid-cols-[1fr_.65fr] items-end gap-[100px] max-[1180px]:grid-cols-[1fr_.7fr] max-[1180px]:gap-[60px] max-[920px]:grid-cols-1 max-[920px]:gap-[38px]"><div><SectionLabel>{label}</SectionLabel><h2 className={`${heading} mt-[38px]`}>{title}</h2></div><div><p className="mb-[26px] max-w-[540px] text-sm leading-[1.7] text-[#626e74]">{copy}</p><TextLink href="/jobs">View All Jobs</TextLink></div></div><div className="mt-[68px] border-t border-line">{jobs.map(([title, location, sector, type, tag]) => <a href="/jobs" key={title} className="group relative grid min-h-[100px] grid-cols-[110px_1.5fr_.8fr_.65fr_.65fr_36px] items-center gap-5 overflow-hidden border-b border-line outline-none before:absolute before:inset-0 before:origin-left before:scale-x-0 before:bg-surface before:transition-transform before:duration-500 before:ease-complex hover:before:scale-x-100 focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-brand-red focus-visible:before:scale-x-100 max-[920px]:grid-cols-[85px_1.2fr_.8fr_.65fr_30px] max-[920px]:[&>span:nth-of-type(2)]:hidden max-[640px]:grid-cols-[1fr_28px] max-[640px]:gap-2 max-[640px]:py-[22px] max-[640px]:[&>span]:col-start-1 max-[640px]:[&>span:nth-of-type(2)]:inline max-[640px]:[&>span:nth-of-type(3)]:inline"><small className="relative z-[1] text-[7px] tracking-[.14em] text-[#9a9fa2] max-[640px]:col-start-1">{tag}</small><strong className="relative z-[1] text-lg tracking-[-.025em] transition-transform duration-300 group-hover:translate-x-[18px] max-[640px]:col-start-1 max-[640px]:text-[17px]">{title}</strong><span className="relative z-[1] text-[11px] text-[#616c72]">{location}</span><span className="relative z-[1] text-[11px] text-[#616c72]">{sector}</span><span className="relative z-[1] text-[11px] text-[#616c72] max-[920px]:hidden max-[640px]:inline">{type}</span><ArrowIcon className="relative z-[1] text-[19px] text-brand-red transition-transform duration-300 group-hover:translate-x-1.5 group-hover:-translate-y-1.5 max-[640px]:col-start-2 max-[640px]:row-start-1 max-[640px]:row-end-5 max-[640px]:self-center" /></a>)}</div></Container></section>;
}

type Cta = { label: string; title: string; copy: string; action: string; href: string };
export function SectorDualCta({ employer, candidate }: { employer: Cta; candidate: Cta }) {
  return <section className="grid grid-cols-2 max-[920px]:grid-cols-1">{[employer, candidate].map((cta, index) => <a href={cta.href} key={cta.label} className={`group/card flex min-h-[470px] flex-col px-[max(50px,calc((100vw-1400px)/2))] py-[54px] text-white outline-none transition-colors duration-500 ease-complex hover:bg-brand-grey focus-visible:bg-brand-grey focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-white max-[920px]:min-h-[420px] max-[920px]:px-[42px] max-[920px]:py-12 max-[640px]:min-h-[390px] max-[640px]:px-6 max-[640px]:py-[38px] ${index === 0 ? 'bg-brand-red pl-[max(40px,calc((100vw-1400px)/2))]' : 'bg-ink pr-[max(40px,calc((100vw-1400px)/2))]'}`}><small className="text-[8px] font-extrabold tracking-[.18em] text-white/65">{cta.label}</small><div className="relative mt-[90px] max-[640px]:mt-[70px]"><span className="absolute bottom-full mb-3 block translate-y-[10px] text-[13px] font-semibold text-white/50 opacity-0 transition duration-300 group-hover/card:translate-y-0 group-hover/card:opacity-100 group-focus-visible/card:translate-y-0 group-focus-visible/card:opacity-100">Hi, Complex,</span><h3 className="m-0 text-[clamp(42px,4vw,68px)] font-semibold leading-[.94] tracking-[-.055em] text-white">{cta.title}</h3></div><p className="mt-5 max-w-[430px] text-xs leading-[1.65] text-white/75">{cta.copy}</p><span className={`group/action mt-auto inline-flex min-h-11 items-center gap-[14px] self-start py-[14px] text-[13px] font-extrabold text-white transition-[background,padding] duration-300 hover:px-4 focus-visible:px-4 ${index === 0 ? 'hover:bg-ink focus-visible:bg-ink' : 'hover:bg-brand-red focus-visible:bg-brand-red'}`}>{cta.action}<ArrowIcon className="transition-transform duration-300 group-hover/action:translate-x-1.5 group-hover/action:-translate-y-[5px]" /></span></a>)}</section>;
}
