import { Footer } from '../../components/layout/Footer';
import { Header } from '../../components/Header';
import { Container } from '../../components/layout/Container';
import { SectionLabel } from '../../components/SectionLabel';
import { ButtonLink } from '../../components/ui/ButtonLink';
import { TextLink } from '../../components/ui/TextLink';

const assessmentSteps = [['01', 'Theory', 'Knowledge and understanding relevant to professional driving.'], ['02', 'Practical', 'On-road and vehicle-based assessment of driving behaviour.'], ['03', 'Feedback', 'Clear observations and recommendations following the assessment.'], ['04', 'Development', 'Training support can be discussed where improvement is needed.']];

export default function TrainingPage() {
  return <main className="bg-white text-ink">
    <section className="grid min-h-[780px] grid-rows-[92px_minmax(0,1fr)_102px] bg-white max-[1000px]:min-h-0 max-[1000px]:grid-rows-[92px_auto_auto] max-[640px]:grid-rows-[76px_auto_auto]">
      <Header active="Training & Assessments" theme="light" />
      <Container className="grid grid-cols-[.9fr_1.1fr] items-center gap-20 py-[52px] max-[1180px]:gap-[58px] max-[1000px]:grid-cols-1 max-[1000px]:py-14 max-[640px]:py-11">
        <div><div className="mb-[34px] text-[10px] font-extrabold tracking-[.2em] text-[#5f686e] before:mr-[13px] before:mb-[3px] before:inline-block before:h-0.5 before:w-9 before:bg-brand-red">TRAINING &amp; ASSESSMENTS <span className="ml-[10px] text-[#9aa0a4] max-[640px]:hidden">/ COMPLEX DRIVING</span></div><h1 className="m-0 text-[clamp(66px,6vw,100px)] leading-[.89] tracking-[-.066em] max-[1180px]:text-[76px] max-[640px]:text-[50px]">Better drivers.<br /><em className="not-italic text-brand-grey">Safer operations<span className="text-brand-red">.</span></em></h1><p className="my-[30px] max-w-[590px] text-[17px] leading-[1.65] text-[#5e6a70]">Practical driver assessments and professional training designed to support safer, more capable transport operations.</p><div className="flex items-center gap-7 max-[430px]:flex-col max-[430px]:items-start max-[430px]:gap-4"><ButtonLink href="#training-services" arrowDirection="down-right">Explore Services</ButtonLink><TextLink href="/contact">Make an Enquiry</TextLink></div></div>
        <div className="relative isolate h-[520px] max-[1180px]:h-[470px] max-[1000px]:h-[430px] max-[640px]:h-[360px]"><div className="absolute left-0 top-0 h-full w-[72%] bg-[linear-gradient(rgba(17,18,20,.04),rgba(17,18,20,.14)),url('https://images.pexels.com/photos/13861/IMG_3496bfree.jpg?auto=compress&cs=tinysrgb&w=1600')] bg-cover bg-center grayscale-[.18] max-[640px]:w-[82%]" /><div className="absolute right-0 top-[66px] h-[62%] w-[42%] bg-[linear-gradient(rgba(17,18,20,.04),rgba(17,18,20,.12)),url('https://images.pexels.com/photos/2199293/pexels-photo-2199293.jpeg?auto=compress&cs=tinysrgb&w=1000')] bg-cover bg-center grayscale-[.18] max-[640px]:top-[42px] max-[640px]:h-[48%] max-[640px]:w-[44%]" /><div className="absolute bottom-0 right-0 min-h-[170px] w-[285px] bg-brand-red p-6 text-white max-[640px]:min-h-[138px] max-[640px]:w-[230px] max-[640px]:p-[18px]"><span className="text-[8px] tracking-[.16em] text-white/70">DRIVER SUPPORT</span><strong className="mt-7 block text-[25px] leading-[1.05] tracking-[-.035em] max-[640px]:mt-5 max-[640px]:text-xl">Assess.<br />Develop.<br />Improve.</strong></div></div>
      </Container>
      <div className="border-t border-line bg-surface max-[640px]:overflow-x-auto"><Container className="grid h-[102px] grid-cols-4 border-l border-line max-[1000px]:grid-cols-2 max-[640px]:h-[82px] max-[640px]:w-[650px] max-[640px]:grid-cols-4">{['Driver Assessments', 'CPC Training', 'Employer Support', 'Professional Development'].map(item => <b className="flex items-center border-r border-line px-[22px] text-[11px]" key={item}>{item}</b>)}</Container></div>
    </section>

    <section className="bg-surface py-[126px] max-[640px]:py-[88px]" id="training-services"><Container><div className="grid grid-cols-[.4fr_1fr] gap-[72px] max-[1180px]:grid-cols-[.3fr_1fr] max-[1180px]:gap-11 max-[640px]:block"><SectionLabel>OUR TRAINING SERVICES</SectionLabel><div className="max-[640px]:mt-7"><h2 className="m-0 text-[clamp(52px,5vw,82px)] leading-[.95] tracking-[-.055em] max-[640px]:text-5xl">Two practical ways to<br /><em className="not-italic text-brand-red">support better drivers.</em></h2><p className="mt-[26px] max-w-[600px] text-sm leading-[1.7] text-[#657177]">Choose the route that fits the requirement. Both services are designed to be clear, practical and easy to discuss with the Complex team.</p></div></div><div className="mt-[70px] grid grid-cols-2 gap-3 max-[1000px]:grid-cols-1">{[
      { href: '/training/driver-assessments', label: '01 / ASSESSMENTS', small: 'FOR EMPLOYERS & DRIVERS', title: <>Driver<br />Assessments</>, copy: 'Practical and theoretical evaluation to understand driver capability, safety and development needs.', image: "url('https://images.pexels.com/photos/4489734/pexels-photo-4489734.jpeg?auto=compress&cs=tinysrgb&w=1800')" },
      { href: '/training/cpc', label: '02 / TRAINING', small: 'PROFESSIONAL DEVELOPMENT', title: <>CPC<br />Training</>, copy: 'Driver-focused professional development that supports competence, knowledge and ongoing standards.', image: "url('https://images.pexels.com/photos/13861/IMG_3496bfree.jpg?auto=compress&cs=tinysrgb&w=1800')" },
    ].map(card => <a href={card.href} key={card.href} className="group relative isolate flex min-h-[600px] flex-col justify-between overflow-hidden p-[30px] text-white outline-none before:absolute before:inset-0 before:-z-[2] before:bg-[linear-gradient(180deg,rgba(17,18,20,.12),rgba(17,18,20,.22)_44%,rgba(17,18,20,.9))] after:absolute after:inset-x-0 after:bottom-0 after:-z-[1] after:h-[55%] after:translate-y-full after:bg-[linear-gradient(180deg,rgba(236,33,37,0),rgba(236,33,37,.14)_36%,rgba(236,33,37,.9))] after:transition-transform after:duration-500 after:ease-complex hover:after:translate-y-0 focus-visible:ring-2 focus-visible:ring-brand-red focus-visible:after:translate-y-0 max-[1000px]:min-h-[500px] max-[640px]:min-h-[430px] max-[640px]:p-[22px]"><div className="absolute inset-[-2%] -z-[3] scale-[1.02] bg-cover bg-center grayscale-[.35] transition-[transform,filter] duration-700 ease-complex group-hover:scale-[1.065] group-hover:grayscale-0 group-focus-visible:scale-[1.065] group-focus-visible:grayscale-0" style={{ backgroundImage: card.image }} /><span className="text-[8px] font-extrabold tracking-[.17em] text-white/70">{card.label}</span><div><small className="text-[8px] font-extrabold tracking-[.17em] text-white/70">{card.small}</small><h3 className="my-[18px] text-[clamp(48px,4.6vw,76px)] leading-[.88] tracking-[-.06em]">{card.title}</h3><p className="max-w-[470px] text-xs leading-[1.6] text-white/80">{card.copy}</p></div><i className="absolute right-7 top-7 text-[23px] not-italic transition-transform duration-300 group-hover:translate-x-[7px] group-hover:-translate-y-[7px] group-focus-visible:translate-x-[7px] group-focus-visible:-translate-y-[7px]">↗</i></a>)}</div></Container></section>

    <section className="bg-white py-[126px] max-[640px]:py-[88px]"><Container className="grid grid-cols-[.62fr_1.38fr] gap-[90px] max-[1180px]:grid-cols-1 max-[1180px]:gap-[54px]"><div><SectionLabel>DRIVER ASSESSMENTS</SectionLabel><h2 className="m-0 mt-[34px] text-[clamp(52px,5vw,82px)] leading-[.95] tracking-[-.055em] max-[640px]:text-5xl">See the driver<br /><em className="not-italic text-brand-red">in context.</em></h2><p className="my-[26px] max-w-[480px] text-sm leading-[1.7] text-[#657178]">Assessments should give employers and drivers useful information — not simply a pass/fail moment.</p><ButtonLink href="/training/driver-assessments" variant="dark">Explore Assessments</ButtonLink></div><div className="grid grid-cols-2 border-l border-t border-line max-[640px]:grid-cols-1">{assessmentSteps.map(([number, title, copy]) => <article className="group min-h-[260px] border-b border-r border-line p-7 transition-colors hover:bg-surface" key={number}><div className="transition-transform duration-300 group-hover:translate-x-[7px]"><span className="text-[8px] font-extrabold text-brand-red">{number}</span><h3 className="mb-3 mt-[74px] text-2xl">{title}</h3><p className="max-w-[270px] text-[11px] leading-[1.6] text-[#69757a]">{copy}</p></div></article>)}</div></Container></section>

    <section className="grid grid-cols-2 bg-ink text-white max-[1000px]:grid-cols-1"><div className="min-h-[650px] bg-[linear-gradient(rgba(17,18,20,.05),rgba(17,18,20,.22)),url('https://images.pexels.com/photos/2199293/pexels-photo-2199293.jpeg?auto=compress&cs=tinysrgb&w=1800')] bg-cover bg-center grayscale-[.18] max-[1000px]:min-h-[430px] max-[640px]:min-h-[330px]" /><div className="px-[max(60px,calc((100vw-1400px)/2))] pb-[100px] pl-20 pt-[110px] max-[1000px]:px-[50px] max-[1000px]:py-[78px] max-[640px]:px-6 max-[640px]:py-[68px] [&_.sectionLabel]:text-white"><SectionLabel>CPC TRAINING</SectionLabel><h2 className="m-0 mt-[34px] text-[clamp(52px,5vw,82px)] leading-[.95] tracking-[-.055em] max-[640px]:text-5xl">Professional development<br /><em className="not-italic text-brand-red">that stays practical.</em></h2><p className="my-7 max-w-[580px] text-[15px] leading-[1.7] text-[#aeb6ba]">Complex can support drivers and employers with CPC-focused training enquiries. The final course structure, dates and delivery details will be populated from approved business information before launch.</p><div className="mb-8 flex flex-wrap gap-2">{['Driver-focused', 'Employer enquiries', 'Clear booking pathway'].map(item => <span className="border border-white/15 px-[13px] py-[11px] text-[9px] text-[#d5d8da]" key={item}>{item}</span>)}</div><ButtonLink href="/training/cpc">Explore CPC Training</ButtonLink></div></section>

    <section className="bg-surface py-[126px] max-[640px]:py-[88px]"><Container className="mb-16 grid grid-cols-[.4fr_1fr] gap-[70px] max-[640px]:block"><SectionLabel>WHO IS IT FOR?</SectionLabel><h2 className="m-0 max-[640px]:mt-7 text-[clamp(52px,5vw,82px)] leading-[.95] tracking-[-.055em] max-[640px]:text-5xl">Support for both sides<br /><em className="not-italic text-brand-red">of the operation.</em></h2></Container><div className="grid grid-cols-2 max-[1000px]:grid-cols-1">{[['FOR EMPLOYERS', 'Strengthen driver standards.', 'Discuss assessments, refresher needs and training support around your transport operation.', 'Make an Enquiry'], ['FOR DRIVERS', 'Keep developing professionally.', 'Explore assessment and training options designed around professional driving.', 'Talk to Complex']].map(([label, title, copy, cta], index) => <article key={label} className={`flex min-h-[420px] flex-col px-[max(48px,calc((100vw-1400px)/2))] py-[46px] text-white max-[1000px]:px-10 max-[1000px]:py-11 max-[640px]:min-h-[370px] max-[640px]:px-6 max-[640px]:py-[38px] ${index === 0 ? 'bg-brand-red' : 'bg-brand-grey'}`}><small className="text-[8px] font-extrabold tracking-[.17em] text-white/70">{label}</small><h3 className="mb-[18px] mt-[84px] max-w-[520px] text-[clamp(38px,3.8vw,60px)] leading-[.95] tracking-[-.05em]">{title}</h3><p className="max-w-[440px] text-xs leading-[1.65] text-white/80">{copy}</p><a className="group mt-auto text-xs font-extrabold outline-none focus-visible:ring-2 focus-visible:ring-white" href="/contact">{cta} <i className="ml-3 inline-block not-italic transition-transform group-hover:translate-x-1.5 group-hover:-translate-y-1.5">↗</i></a></article>)}</div></section>

    <section className="bg-white py-[120px] max-[640px]:py-[88px]"><Container className="grid grid-cols-[1fr_.62fr] items-end gap-[100px] max-[1000px]:grid-cols-1 max-[1000px]:gap-11"><div><SectionLabel>START A CONVERSATION</SectionLabel><h2 className="m-0 mt-[34px] text-[clamp(52px,5vw,82px)] leading-[.95] tracking-[-.055em] max-[640px]:text-5xl">Need training or<br /><em className="not-italic text-brand-red">an assessment?</em></h2></div><div><p className="mb-7 max-w-[550px] text-[15px] leading-[1.7] text-[#657178]">Tell us whether you are enquiring as an employer or driver and what support you need. The Complex team can advise on the next step.</p><ButtonLink href="/contact">Make an Enquiry</ButtonLink></div></Container></section>
    <Footer variant="training" />
  </main>;
}
