import { BusinessOperationalRoleExplorer } from '../../../components/BusinessOperationalRoleExplorer';
import { Footer } from '../../../components/layout/Footer';
import { SectorHero } from '../../../components/sectors/SectorHero';
import { SectorCompliance, SectorDualCta, SectorIntro, SectorJobs, SectorProcess, SectorRoles, SectorService } from '../../../components/sectors/SectorSections';

const serviceItems = ['Temporary & ad-hoc support', 'Temp-to-perm recruitment', 'Permanent recruitment', 'High-volume requirements', 'Targeted candidate sourcing', 'Role and shift matching'];

export default function BusinessOperationalSupportPage() {
  return <main className="bg-white text-ink">
    <SectorHero compactTitle sector="Business & Operational Support" title={<>The people behind<br/><em>your operation.</em></>} description="Complex recruits the planners, administrators, coordinators and support teams that keep transport, logistics, warehousing and operational businesses moving." requestLabel="Request Support Staff" jobsLabel="Find Support Work" jobsHref="/jobs" proofLabel="OPERATIONAL SUPPORT" proofCopy="People who understand the pace and priorities behind physical operations." rail={['Transport Planning','Administration','Coordination','Customer Service','Supervision']} images={['https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=2200','https://images.pexels.com/photos/3183150/pexels-photo-3183150.jpeg?auto=compress&cs=tinysrgb&w=2200']} positions={['center 46%','center 42%']} />
    <SectorIntro label="BUSINESS & OPERATIONAL SUPPORT" title={<>Operational support<br/><em>behind the workforce.</em></>} copy="Strong operations rely on the people coordinating schedules, systems, customers and teams. Complex focuses on support roles that sit close to transport, logistics, warehousing and other operational environments." proof={[["01","Operations-led","Recruitment shaped around working patterns, systems and operational priorities."],["02","Sector-connected","Candidates selected for environments Complex already understands."],["03","Flexible solutions","Temporary, temp-to-perm, permanent and volume support where required."],["04","Practical matching","Experience, communication and shift requirements considered together."]]} />
    <SectorRoles label="SUPPORT JOB CATEGORIES" title={<>The roles that keep<br/><em>operations connected.</em></>} copy="Explore the planning, administration, customer service and leadership roles that support day-to-day operational performance."><BusinessOperationalRoleExplorer /></SectorRoles>
    <SectorCompliance image="https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=1800" label="WHAT WE LOOK FOR" title={<>Ready for the role.<br/><em>Right for the operation.</em></>} copy="The right match combines practical capability with an understanding of the environment in which the work happens." checks={['Relevant sector or operational experience','Familiarity with the systems used in the role','Flexibility around shifts and operating hours','Clear, confident communication','Understanding of operational priorities']} button="Request Support Staff" />
    <SectorService title={<>Recruitment shaped around<br/><em>operational demand.</em></>} copy="From short-term coordination cover to permanent operational hires, the route is matched to the requirement." items={serviceItems} />
    <SectorProcess label="FROM BRIEF TO PLACEMENT" title={<>A focused route to<br/><em>the right support.</em></>} steps={[["01","Understand","Confirm the role, environment, systems, working pattern and priorities."],["02","Source","Reach suitable candidates through targeted search and existing networks."],["03","Assess","Review relevant experience, communication and operational understanding."],["04","Place & support","Coordinate the placement and keep communication clear after the start."]]} />
    <SectorJobs id="business-support-jobs" label="BUSINESS & OPERATIONAL SUPPORT OPPORTUNITIES" title={<>Current roles behind<br/><em>the operation.</em></>} copy="Live roles will be pulled from the jobs CMS and filtered automatically to Business & Operational Support." jobs={[["Transport Planner","London","Business Support","Permanent","CMS PREVIEW"],["Warehouse Administrator","Enfield","Business Support","Temporary","CMS PREVIEW"],["Operations Coordinator","Greater London","Business Support","Temp-to-perm","CMS PREVIEW"]]} />
    <SectorDualCta employer={{label:'FOR EMPLOYERS',title:'I need support staff.',copy:'Tell us the role, environment, working pattern and timing. We’ll take it from there.',action:'Request Staff',href:'/request-staff'}} candidate={{label:'FOR CANDIDATES',title:'I’m looking for support work.',copy:'Explore operational administration, planning, customer service and leadership roles.',action:'Find Support Jobs',href:'/jobs'}} />
    <Footer />
  </main>;
}
