import { IndustrialRoleExplorer } from '../../../components/IndustrialRoleExplorer';
import { Footer } from '../../../components/layout/Footer';
import { SectorHero } from '../../../components/sectors/SectorHero';
import { SectorCompliance, SectorDualCta, SectorIntro, SectorJobs, SectorProcess, SectorRoles, SectorService } from '../../../components/sectors/SectorSections';

const serviceItems = ['Daily check-in confirmation','Management of rotas','Weekly onsite staff welfare sessions','Training workshops','Weekly management information','Monthly compliance log','Worker performance reviews','Buddy system'];

export default function IndustrialPage() {
  return <main className="bg-white text-ink">
    <SectorHero compactTitle sector="Industrial & Warehouse" title={<>Industrial teams.<br/><em>At your pace.</em></>} description="Reliable temporary and permanent workforce solutions across warehousing, logistics, production, engineering and retail environments." requestLabel="Request Industrial Staff" jobsLabel="Find Industrial Work" jobsHref="/jobs" proofLabel="OPERATIONAL SUPPORT" proofCopy="Flexible staffing support for fast-moving industrial requirements." rail={['Warehouse','FLT','Production','Picking & Packing','Supervisory']} images={['https://images.pexels.com/photos/1267338/pexels-photo-1267338.jpeg?auto=compress&cs=tinysrgb&w=2200','https://images.pexels.com/photos/6169669/pexels-photo-6169669.jpeg?auto=compress&cs=tinysrgb&w=2200']} positions={['center 52%','center 42%']} />
    <SectorIntro label="WHY COMPLEX INDUSTRIAL" title={<>Flexible workforce.<br/><em>Operationally ready.</em></>} copy="Complex Industrial supports clients with reliable staff and service models shaped around different operating pressures — from daily supply and urgent peaks to fully managed workforce requirements." proof={[["01","Temporary & Ad-hoc","Rapid access to workers for peaks, absence cover and changing volume."],["02","Permanent","Longer-term recruitment for operational and supervisory roles."],["03","Skills-matched","Candidates aligned to the practical requirements of the environment."],["04","Dedicated support","Account management and 24/7 response for changing requirements."]]} />
    <SectorRoles label="INDUSTRIAL JOB CATEGORIES" title={<>From warehouse teams<br/><em>to operational support.</em></>} copy="Explore the kinds of warehouse, logistics, material-handling and production roles supported by the Industrial division."><IndustrialRoleExplorer /></SectorRoles>
    <SectorCompliance image="https://images.pexels.com/photos/4483608/pexels-photo-4483608.jpeg?auto=compress&cs=tinysrgb&w=1800" label="WORKFORCE READINESS" title={<>Right people.<br/><em>Right preparation.</em><br/>Ready to perform.</>} copy="Complex works around each client’s regulatory and operational requirements so workers arrive briefed, appropriately checked and prepared for the role." checks={['Pre-screening for suitability and relevant work history','Eligibility and role-specific compliance checks','Skills matching around the client requirement','Site and role-specific assignment overview','Performance reviews and upskilling support','Management information around productivity, fulfilment and retention']} button="Request Industrial Staff" />
    <SectorService title={<>Support beyond<br/><em>the first shift.</em></>} copy="Complex’s Industrial service model combines workforce supply with practical account support throughout the assignment." items={serviceItems} />
    <SectorProcess label="FROM REQUIREMENT TO WORKFORCE" title={<>Built around changing<br/><em>operational demand.</em></>} steps={[["01","Brief us","Role, location, shift, numbers and timing."],["02","Match & prepare","Suitable workers are identified, checked and briefed."],["03","Deploy","Assignments are confirmed and attendance is supported."],["04","Stay involved","Complex manages communication, welfare and service information."]]} />
    <SectorJobs id="industrial-jobs" label="INDUSTRIAL OPPORTUNITIES" title={<>Current roles<br/><em>across industry.</em></>} copy="Live roles will be pulled from the new jobs CMS and filtered automatically to the Industrial division." jobs={[["Warehouse Operative","Hayes","Industrial","Temporary","CMS PREVIEW"],["Forklift Driver","Heston","Industrial","Temporary","CMS PREVIEW"],["Warehouse Supervisor","London","Industrial","Permanent","CMS PREVIEW"]]} />
    <SectorDualCta employer={{ label:'FOR EMPLOYERS', title:'I need industrial staff.', copy:'Tell us the role, shift, numbers and timing. We’ll take it from there.', action:'Request Staff', href:'/request-staff' }} candidate={{ label:'FOR CANDIDATES', title:'I’m looking for industrial work.', copy:'Explore warehouse, logistics and production opportunities.', action:'Find Industrial Jobs', href:'/jobs' }} />
    <Footer />
  </main>;
}
